# Generated by Django 3.0.3 on 2020-10-30 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chat_contact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
    ]
