# Generated by Django 3.0.3 on 2020-10-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201030_0847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
